In [1]:
import os
import pandas as pd

folder_path = "C:/Users/ttma9/downloads/Brawlstars_project-main-20230313T042453Z-001/Brawlstars_project-main"


csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]


dfs = []

for file in csv_files:
    df = pd.read_csv(os.path.join(folder_path, file))
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)

merged_df = merged_df.drop(merged_df.columns[0], axis=1)

merged_df

,battle_time,mode,map,type,duration,player_tag,player_name,player_trophies,player_top_brawler,star_player,team,result,rank,brawler_id,brawler_name,brawler_power,brawler_star_power,brawler_gadget,brawler_trophies
0,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#U2RGPGLV,PanCake,54300,NITA,0,2,victory,NaN,16000012,CROW,11,1,1,942
1,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#2L0G9RVQ9,YOUYOUYTB,60805,SHELLY,0,2,victory,NaN,16000047,SQUEAK,11,1,1,906
2,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#22GR90YCV,Lyrexs64,58061,ASH,0,2,victory,NaN,16000059,OTIS,11,1,1,905
3,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#GJU2P028,sweetfear,51481,OTIS,1,1,victory,NaN,16000029,BEA,11,1,1,1025
4,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#VLQPVPY,Hyra,71910,R-T,0,1,victory,NaN,16000002,BULL,11,1,1,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65293,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#P9VJ8QYRR,KewSaai,42858,PIPER,0,1,victory,NaN,16000044,RUFFS,11,1,1,16
65294,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#RGVJQVRL,TKZCRUSHER,38021,LEON,0,1,victory,NaN,16000012,CROW,11,1,1,16
65295,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#208V908QL,Trol,58952,POCO,0,2,victory,NaN,16000038,SURGE,11,1,1,17
65296,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#20RLLR88Y,ByTopinC,56154,BIBI,0,2,victory,NaN,16000029,BEA,11,1,1,16
65297,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#PJQYJJU,Hazzah,47589,STU,0,2,victory,NaN,16000021,GENE,11,1,1,16

In [2]:
df = merged_df.copy()

In [9]:
df=df[~df['result'].isna()]
df

,battle_time,mode,map,type,duration,player_tag,player_name,player_trophies,player_top_brawler,star_player,team,result,rank,brawler_id,brawler_name,brawler_power,brawler_star_power,brawler_gadget,brawler_trophies
0,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#U2RGPGLV,PanCake,54300,NITA,0,2,victory,NaN,16000012,CROW,11,1,1,942
1,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#2L0G9RVQ9,YOUYOUYTB,60805,SHELLY,0,2,victory,NaN,16000047,SQUEAK,11,1,1,906
2,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#22GR90YCV,Lyrexs64,58061,ASH,0,2,victory,NaN,16000059,OTIS,11,1,1,905
3,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#GJU2P028,sweetfear,51481,OTIS,1,1,victory,NaN,16000029,BEA,11,1,1,1025
4,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#VLQPVPY,Hyra,71910,R-T,0,1,victory,NaN,16000002,BULL,11,1,1,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65293,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#P9VJ8QYRR,KewSaai,42858,PIPER,0,1,victory,NaN,16000044,RUFFS,11,1,1,16
65294,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#RGVJQVRL,TKZCRUSHER,38021,LEON,0,1,victory,NaN,16000012,CROW,11,1,1,16
65295,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#208V908QL,Trol,58952,POCO,0,2,victory,NaN,16000038,SURGE,11,1,1,17
65296,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#20RLLR88Y,ByTopinC,56154,BIBI,0,2,victory,NaN,16000029,BEA,11,1,1,16
65297,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#PJQYJJU,Hazzah,47589,STU,0,2,victory,NaN,16000021,GENE,11,1,1,16

In [13]:
df.drop(columns=['rank','brawler_id'],axis=1,inplace=True)
df

,battle_time,mode,map,type,duration,player_tag,player_name,player_trophies,player_top_brawler,star_player,team,result,brawler_name,brawler_power,brawler_star_power,brawler_gadget,brawler_trophies
0,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#U2RGPGLV,PanCake,54300,NITA,0,2,victory,CROW,11,1,1,942
1,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#2L0G9RVQ9,YOUYOUYTB,60805,SHELLY,0,2,victory,SQUEAK,11,1,1,906
2,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#22GR90YCV,Lyrexs64,58061,ASH,0,2,victory,OTIS,11,1,1,905
3,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#GJU2P028,sweetfear,51481,OTIS,1,1,victory,BEA,11,1,1,1025
4,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#VLQPVPY,Hyra,71910,R-T,0,1,victory,BULL,11,1,1,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65293,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#P9VJ8QYRR,KewSaai,42858,PIPER,0,1,victory,RUFFS,11,1,1,16
65294,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#RGVJQVRL,TKZCRUSHER,38021,LEON,0,1,victory,CROW,11,1,1,16
65295,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#208V908QL,Trol,58952,POCO,0,2,victory,SURGE,11,1,1,17
65296,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#20RLLR88Y,ByTopinC,56154,BIBI,0,2,victory,BEA,11,1,1,16
65297,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#PJQYJJU,Hazzah,47589,STU,0,2,victory,GENE,11,1,1,16

In [16]:
def get_result(row):
    if row['team'] == 1:
        if row['result'] == 'victory':
            return 'win'
        else:
            return 'defeat'
    else:
        if row['result'] == 'victory':
            return 'defeat'
        else:
            return 'win'

df['new_result'] = df.apply(get_result, axis=1)
df

,battle_time,mode,map,type,duration,player_tag,player_name,player_trophies,player_top_brawler,star_player,team,result,brawler_name,brawler_power,brawler_star_power,brawler_gadget,brawler_trophies,new_result
0,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#U2RGPGLV,PanCake,54300,NITA,0,2,victory,CROW,11,1,1,942,defeat
1,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#2L0G9RVQ9,YOUYOUYTB,60805,SHELLY,0,2,victory,SQUEAK,11,1,1,906,defeat
2,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#22GR90YCV,Lyrexs64,58061,ASH,0,2,victory,OTIS,11,1,1,905,defeat
3,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#GJU2P028,sweetfear,51481,OTIS,1,1,victory,BEA,11,1,1,1025,win
4,20230309T025215.000Z,brawlBall,Pinhole Punt,ranked,29.0,#VLQPVPY,Hyra,71910,R-T,0,1,victory,BULL,11,1,1,1156,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65293,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#P9VJ8QYRR,KewSaai,42858,PIPER,0,1,victory,RUFFS,11,1,1,16,win
65294,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#RGVJQVRL,TKZCRUSHER,38021,LEON,0,1,victory,CROW,11,1,1,16,win
65295,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#208V908QL,Trol,58952,POCO,0,2,victory,SURGE,11,1,1,17,defeat
65296,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#20RLLR88Y,ByTopinC,56154,BIBI,0,2,victory,BEA,11,1,1,16,defeat
65297,20230308T142501.000Z,gemGrab,Double Swoosh,soloRanked,119.0,#PJQYJJU,Hazzah,47589,STU,0,2,victory,GENE,11,1,1,16,defeat

In [26]:
player_map_win_rates = df.groupby(['player_tag', 'map'])['new_result'].apply(lambda x: (x=='win').sum() / len(x)).reset_index()
player_map_win_rates.rename(columns={'new_result': 'win_rate'}, inplace=True)

# Print results 
print("player_tag 따른 맵별 승률:")
player_map_win_rates

player_tag 따른 맵별 승률:

       player_tag             map  win_rate
0       #20000RCJ  Crystal Arcade       0.0
1      #2000GJJVG      Field Goal       1.0
2      #2002CLLRJ   Kaboom Canyon       0.0
3      #2002VQRQP           Split       0.0
4      #20089JR2J  Hard Rock Mine       1.0
...           ...             ...       ...
16904  #YYVLJ2J09    Pinhole Punt       0.0
16905  #YYVRCCLP8      Iron Cover       0.0
16906   #YYVYGJ92           Split       1.0
16907   #YYY8GLG2    Iron Curtain       0.0
16908   #YYYQJ8VG    Pinhole Punt       0.0

[16909 rows x 3 columns]

In [27]:
brawler_mode_win_rates = df.groupby(['brawler_name', 'mode'])['new_result'].apply(lambda x: (x=='win').sum() / len(x)).reset_index()
brawler_mode_win_rates.rename(columns={'new_result': 'win_rate'}, inplace=True)

print("브롤러에따른 모드별 승률:")
brawler_mode_win_rates

브롤러에따른 모드별 승률:

    brawler_name         mode  win_rate
0          8-BIT  basketBrawl  0.444444
1          8-BIT       bounty  0.142857
2          8-BIT    brawlBall  0.506494
3          8-BIT      gemGrab  0.467105
4          8-BIT        heist  0.459459
..           ...          ...       ...
442         TICK    brawlBall  0.151899
443         TICK      gemGrab  0.238938
444         TICK        heist  0.000000
445         TICK      hotZone  0.200608
446         TICK     knockout  0.494737

[447 rows x 3 columns]

In [28]:
brawler_map_win_rates = df.groupby(['brawler_name', 'map'])['new_result'].apply(lambda x: (x=='win').sum() / len(x)).reset_index()
brawler_map_win_rates.rename(columns={'new_result': 'win_rate'}, inplace=True)

print("브롤러에따른 모드별 승률:")
brawler_map_win_rates

브롤러에따른 모드별 승률:

     brawler_name             map  win_rate
0           8-BIT     Acute Angle  1.000000
1           8-BIT   Backyard Bowl  0.000000
2           8-BIT  Bridge Too Far  0.222222
3           8-BIT    Canal Grande  0.000000
4           8-BIT  Center Control  0.111111
...           ...             ...       ...
1749         TICK    Ring of Fire  0.142857
1750         TICK   Shooting Star  0.294118
1751         TICK    Solid Center  0.400000
1752         TICK           Split  0.183391
1753         TICK    Step by Step  0.217391

[1754 rows x 3 columns]

In [21]:
brawler_mode_win_rates.to_csv('mode_winrate.csv')

In [23]:
brawler_map_win_rates.to_csv('map_winrate.csv')

In [25]:
brawler_map_win_rates[brawler_map_win_rates['map']=='Split'].to_csv('split.csv')